version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - ./.env
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 