version: '3.8'

services:
  workspace:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb

volumes:
  mongodb_data: 